url: https://jhancock532.github.io/
title: James's Web Log
description: Writing whilst studying Digital Media Arts at Brighton University
name: James Hancock
logo: https://www.starwheels.com/images/image/L48.jpg

theme: jekyll-theme-minimal
