url: https://jhancock532.github.io/
title: James's Web Log
description: A blog created whilst studying Digital Media Arts at the University of Brighton.
name: James Hancock

theme: jekyll-theme-minimal
